### ISSUE TITLE
Not updating the pr with a comment 

### ISSUE THREAD

**Issue by twij2332** [veracode/Veracode-pipeline-scan-action#4]
Hi

I used pipeline scan action in my github workflow as below and when I am using it with 'fail_on_severity' option it will not show any output in pipeline it self or as a comment in PR 

Here is my github workflow
      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.3
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: "file.zip" 
          fail_on_severity: 'true'

If I run without fail_on_severity: 'true' it will add a comment to pr like this 
![Screenshot_20230607_013828_Chrome](https://github.com/veracode/Veracode-pipeline-scan-action/assets/106312789/4dce63e3-4b55-4108-98c5-d2269f9e958a)

**Comment by nadimz** [comment]
The syntax for `fail_on_severity` according to the documentation in [action.yaml](https://github.com/veracode/Veracode-pipeline-scan-action/blob/master/action.yml) is:
```
fail_on_severity:
    description: 'Fail the pipeline job if the scan finds flaws of the specified severities. Enter a comma-separated list of severities in quotation marks.'
```

So, if you want the build to fail only when `High` or `Very High` issues are found, you'd do this:
```
- name: 🛡️ Run Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: app.zip
          fail_on_severity: "Very High, High"
          fail_build: true
```

However, there's currently a parsing bug and `fail_on_severity` doesn't work. I have PR #30 for it.
